# Generated by Django 5.0.6 on 2024-05-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_assignments_assignment_rename_grades_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
    ]
