# Generated by Django 5.0.6 on 2024-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_role_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Te', 'Teacher'), ('Of', 'Office'), ('Pa', 'Parent'), ('St', 'Student')], default='St', max_length=2),
        ),
    ]
