# Generated by Django 5.0.6 on 2024-05-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ManyToManyField(related_name='members', to='main.room'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
